var tema = 0
function trocaTema(){
  if(tema === 0){
    document.getElementById("conteudo").style.backgroundColor="rgb(60,60,60)";
    document.getElementById("logo").style.display="none";
    document.getElementById("logow").style.display="flex";
    document.getElementById("bvw").style.display="flex";
    document.getElementById("bv").style.display="none";
    document.getElementById("trcTema").style.color="black";
    document.getElementById("enviar").style.color="black";
    document.getElementById("trcTema").style.backgroundColor="white";
    document.getElementById("trcTema").innerHTML="White"
    document.getElementById("nav").style.backgroundColor="rgb(20, 20, 20)"
    document.getElementById("main").style.backgroundColor="rgb(40, 40, 40)"
    document.getElementById("tp1").style.color="white";
    document.getElementById("tp2").style.color="white";
    document.getElementById("tp3").style.color="white";
    document.getElementById("tp4").style.color="white";
    document.getElementById("tp5").style.color="white";
    document.getElementById("tp6").style.color="white";
    document.getElementById("tp7").style.color="white";
    document.getElementById("tp8").style.color="white";
    document.getElementById("p1").style.color="white";
    document.getElementById("p2").style.color="white";
    document.getElementById("p3").style.color="white";
    document.getElementById("p4").style.color="white";
    document.getElementById("p5").style.color="white";
    document.getElementById("p6").style.color="white";
    document.getElementById("p7").style.color="white";
    document.getElementById("p8").style.color="white";
    document.getElementById("p9").style.color="white";
    document.getElementById("p10").style.color="white";
    document.getElementById("p11").style.color="white";
    document.getElementById("p12").style.color="white";
    document.getElementById("p13").style.color="white";
    document.getElementById("p14").style.color="white";
    document.getElementById("p15").style.color="white";
    document.getElementById("p16").style.color="white";
    document.getElementById("p18").style.color="white";
    document.getElementById("p19").style.color="white";
    tema = 1
  }else{
    document.getElementById("conteudo").style.backgroundColor="white";
    document.getElementById("logo").style.display="flex";
    document.getElementById("logow").style.display="none";
    document.getElementById("bvw").style.display="none";
    document.getElementById("bv").style.display="flex";
    document.getElementById("trcTema").style.color="white";
    document.getElementById("enviar").style.color="white";
    document.getElementById("trcTema").style.backgroundColor="black";
    document.getElementById("trcTema").innerHTML="Dark"
    document.getElementById("nav").style.backgroundColor="rgb(210, 210, 210)"
    document.getElementById("main").style.backgroundColor="rgb(236, 236, 236)"
    document.getElementById("tp1").style.color="black";
    document.getElementById("tp2").style.color="black";
    document.getElementById("tp3").style.color="black";
    document.getElementById("tp4").style.color="black";
    document.getElementById("tp5").style.color="black";
    document.getElementById("tp6").style.color="black";
    document.getElementById("tp7").style.color="black";
    document.getElementById("tp8").style.color="black";
    document.getElementById("p1").style.color="black";
    document.getElementById("p2").style.color="black";
    document.getElementById("p3").style.color="black";
    document.getElementById("p4").style.color="black";
    document.getElementById("p5").style.color="black";
    document.getElementById("p6").style.color="black";
    document.getElementById("p7").style.color="black";
    document.getElementById("p8").style.color="black";
    document.getElementById("p9").style.color="black";
    document.getElementById("p10").style.color="black";
    document.getElementById("p11").style.color="black";
    document.getElementById("p12").style.color="black";
    document.getElementById("p13").style.color="black";
    document.getElementById("p14").style.color="black";
    document.getElementById("p15").style.color="black";
    document.getElementById("p16").style.color="black";
    document.getElementById("p18").style.color="black";
    document.getElementById("p19").style.color="black";
    tema = 0
  }
}

function trocaTemaRed(){
  document.getElementById("conteudo").style.backgroundColor="rgb(150, 0, 0)";
    document.getElementById("logo").style.display="none";
    document.getElementById("logow").style.display="flex";
    document.getElementById("bvw").style.display="flex";
    document.getElementById("bv").style.display="none";
    document.getElementById("trcTema").style.color="black";
    document.getElementById("enviar").style.color="black";
    document.getElementById("trcTema").style.backgroundColor="white";
    document.getElementById("trcTema").innerHTML="White"
    document.getElementById("nav").style.backgroundColor="red"
    document.getElementById("main").style.backgroundColor="rgb(190, 0, 0)"
    document.getElementById("tp1").style.color="white";
    document.getElementById("tp2").style.color="white";
    document.getElementById("tp3").style.color="white";
    document.getElementById("tp4").style.color="white";
    document.getElementById("tp5").style.color="white";
    document.getElementById("tp6").style.color="white";
    document.getElementById("tp7").style.color="white";
    document.getElementById("tp8").style.color="white";
    document.getElementById("p1").style.color="white";
    document.getElementById("p2").style.color="white";
    document.getElementById("p3").style.color="white";
    document.getElementById("p4").style.color="white";
    document.getElementById("p5").style.color="white";
    document.getElementById("p6").style.color="white";
    document.getElementById("p7").style.color="white";
    document.getElementById("p8").style.color="white";
    document.getElementById("p9").style.color="white";
    document.getElementById("p10").style.color="white";
    document.getElementById("p11").style.color="white";
    document.getElementById("p12").style.color="white";
    document.getElementById("p13").style.color="white";
    document.getElementById("p14").style.color="white";
    document.getElementById("p15").style.color="white";
    document.getElementById("p16").style.color="white";
    document.getElementById("p18").style.color="white";
    document.getElementById("p19").style.color="white";
}

function trocaTemaBlue(){
  document.getElementById("conteudo").style.backgroundColor="rgb(0, 0, 150)";
    document.getElementById("logo").style.display="none";
    document.getElementById("logow").style.display="flex";
    document.getElementById("bvw").style.display="flex";
    document.getElementById("bv").style.display="none";
    document.getElementById("trcTema").style.color="black";
    document.getElementById("enviar").style.color="black";
    document.getElementById("trcTema").style.backgroundColor="white";
    document.getElementById("trcTema").innerHTML="White"
    document.getElementById("nav").style.backgroundColor="blue"
    document.getElementById("main").style.backgroundColor="rgb(0, 0, 190)"
    document.getElementById("tp1").style.color="white";
    document.getElementById("tp2").style.color="white";
    document.getElementById("tp3").style.color="white";
    document.getElementById("tp4").style.color="white";
    document.getElementById("tp5").style.color="white";
    document.getElementById("tp6").style.color="white";
    document.getElementById("tp7").style.color="white";
    document.getElementById("tp8").style.color="white";
    document.getElementById("p1").style.color="white";
    document.getElementById("p2").style.color="white";
    document.getElementById("p3").style.color="white";
    document.getElementById("p4").style.color="white";
    document.getElementById("p5").style.color="white";
    document.getElementById("p6").style.color="white";
    document.getElementById("p7").style.color="white";
    document.getElementById("p8").style.color="white";
    document.getElementById("p9").style.color="white";
    document.getElementById("p10").style.color="white";
    document.getElementById("p11").style.color="white";
    document.getElementById("p12").style.color="white";
    document.getElementById("p13").style.color="white";
    document.getElementById("p14").style.color="white";
    document.getElementById("p15").style.color="white";
    document.getElementById("p16").style.color="white";
    document.getElementById("p18").style.color="white";
    document.getElementById("p19").style.color="white";
}

function trocaTemaGreen(){
  document.getElementById("conteudo").style.backgroundColor="green";
    document.getElementById("logo").style.display="none";
    document.getElementById("logow").style.display="flex";
    document.getElementById("bvw").style.display="flex";
    document.getElementById("bv").style.display="none";
    document.getElementById("trcTema").style.color="black";
    document.getElementById("enviar").style.color="black";
    document.getElementById("trcTema").style.backgroundColor="white";
    document.getElementById("trcTema").innerHTML="White"
    document.getElementById("nav").style.backgroundColor="rgb(0, 190, 0)"
    document.getElementById("main").style.backgroundColor="rgb(0, 150, 0)"
    document.getElementById("tp1").style.color="white";
    document.getElementById("tp2").style.color="white";
    document.getElementById("tp3").style.color="white";
    document.getElementById("tp4").style.color="white";
    document.getElementById("tp5").style.color="white";
    document.getElementById("tp6").style.color="white";
    document.getElementById("tp7").style.color="white";
    document.getElementById("tp8").style.color="white";
    document.getElementById("p1").style.color="white";
    document.getElementById("p2").style.color="white";
    document.getElementById("p3").style.color="white";
    document.getElementById("p4").style.color="white";
    document.getElementById("p5").style.color="white";
    document.getElementById("p6").style.color="white";
    document.getElementById("p7").style.color="white";
    document.getElementById("p8").style.color="white";
    document.getElementById("p9").style.color="white";
    document.getElementById("p10").style.color="white";
    document.getElementById("p11").style.color="white";
    document.getElementById("p12").style.color="white";
    document.getElementById("p13").style.color="white";
    document.getElementById("p14").style.color="white";
    document.getElementById("p15").style.color="white";
    document.getElementById("p16").style.color="white";
    document.getElementById("p18").style.color="white";
    document.getElementById("p19").style.color="white";
}

function trocaTemaYellow(){
  document.getElementById("conteudo").style.backgroundColor="rgb(170, 170, 0)";
    document.getElementById("logo").style.display="none";
    document.getElementById("logow").style.display="flex";
    document.getElementById("bvw").style.display="flex";
    document.getElementById("bv").style.display="none";
    document.getElementById("trcTema").style.color="black";
    document.getElementById("enviar").style.color="black";
    document.getElementById("trcTema").style.backgroundColor="white";
    document.getElementById("trcTema").innerHTML="White"
    document.getElementById("nav").style.backgroundColor="rgb(220, 220, 0)"
    document.getElementById("main").style.backgroundColor="rgb(200, 200, 0)"
    document.getElementById("tp1").style.color="white";
    document.getElementById("tp2").style.color="white";
    document.getElementById("tp3").style.color="white";
    document.getElementById("tp4").style.color="white";
    document.getElementById("tp5").style.color="white";
    document.getElementById("tp6").style.color="white";
    document.getElementById("tp7").style.color="white";
    document.getElementById("tp8").style.color="white";
    document.getElementById("p1").style.color="white";
    document.getElementById("p2").style.color="white";
    document.getElementById("p3").style.color="white";
    document.getElementById("p4").style.color="white";
    document.getElementById("p5").style.color="white";
    document.getElementById("p6").style.color="white";
    document.getElementById("p7").style.color="white";
    document.getElementById("p8").style.color="white";
    document.getElementById("p9").style.color="white";
    document.getElementById("p10").style.color="white";
    document.getElementById("p11").style.color="white";
    document.getElementById("p12").style.color="white";
    document.getElementById("p13").style.color="white";
    document.getElementById("p14").style.color="white";
    document.getElementById("p15").style.color="white";
    document.getElementById("p16").style.color="white";
    document.getElementById("p18").style.color="white";
    document.getElementById("p19").style.color="white";
}
